spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coin?characterEncoding=UTF-8
    username: root
    password: test

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    database-platform: org.hibernate.dialect.MariaDB103Dialect
